# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"train": "00_train.ipynb",
         "train_parallel": "00_train.ipynb",
         "CounterfactualModel2OptimizersW": "00_train.ipynb",
         "dict2json": "02_data.ipynb",
         "load_json": "02_data.ipynb",
         "update_json_file": "02_data.ipynb",
         "bn_func": "02_data.ipynb",
         "x1_to_x3": "02_data.ipynb",
         "x1x2_to_x4": "02_data.ipynb",
         "bn_gen": "02_data.ipynb",
         "load_adult_income_dataset": "02_data.ipynb",
         "load_learning_analytic_data": "02_data.ipynb",
         "NumpyDataset": "02_data.ipynb",
         "PandasDataset": "02_data.ipynb",
         "pl_logger": "05b_evaluate.ipynb",
         "DataModule": "03b_counterfactual_net.ipynb",
         "uniform": "03b_counterfactual_net.ipynb",
         "BaselineTrainingModule": "03b_counterfactual_net.ipynb",
         "hinge_loss": "03b_counterfactual_net.ipynb",
         "cat_normalize": "03b_counterfactual_net.ipynb",
         "l1_mean": "03b_counterfactual_net.ipynb",
         "get_loss_functions": "03b_counterfactual_net.ipynb",
         "get_optimizers": "03b_counterfactual_net.ipynb",
         "smooth_y": "03b_counterfactual_net.ipynb",
         "CounterfactualTrainingModule": "03b_counterfactual_net.ipynb",
         "LossWrapper": "03b_counterfactual_net.ipynb",
         "CounterfactualTrainingModuleLossWrapper": "03b_counterfactual_net.ipynb",
         "CounterfactualTrainingModule2Optimizers": "03b_counterfactual_net.ipynb",
         "LinearBlock": "03b_counterfactual_net.ipynb",
         "MultilayerPerception": "03b_counterfactual_net.ipynb",
         "BaselineModel": "03b_counterfactual_net.ipynb",
         "CounterfactualModel": "03b_counterfactual_net.ipynb",
         "CounterfactualModel2Optimizers": "03b_counterfactual_net.ipynb",
         "Clamp": "05a_baseline_algos.ipynb",
         "ExplainerBase": "05a_baseline_algos.ipynb",
         "VanillaCF": "05a_baseline_algos.ipynb",
         "DiverseCF": "05a_baseline_algos.ipynb",
         "AE": "05a_baseline_algos.ipynb",
         "ProtoCF": "05a_baseline_algos.ipynb",
         "VAE": "05a_baseline_algos.ipynb",
         "VAE_CF": "05a_baseline_algos.ipynb",
         "load_model": "05b_evaluate.ipynb",
         "load_model_jupyter": "05b_evaluate.ipynb",
         "proximity": "05b_evaluate.ipynb",
         "cf_gen_parallel": "05b_evaluate.ipynb",
         "model_cf_gen": "05b_evaluate.ipynb",
         "evaluate": "05b_evaluate.ipynb",
         "test_evaluate": "05b_evaluate.ipynb"}

modules = ["train.py",
           "utils.py",
           "net.py",
           "training_module.py",
           "baseline.py",
           "evaluate.py"]

doc_url = "https://birkhoffg.github.io/counterfactual/"

git_url = "https://github.com/birkhoffg/counterfactual/tree/master/"

def custom_doc_links(name): return None
